remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "MVTrans: Multi-View Perception of Transparent Objects"
description: <a href="https://www.linkedin.com/in/yi-ru-helen-wang/">Yi Ru Wang</a>